# Generated by Django 6.0.6 on 2026-06-13 13:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_package_room'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='guideprofile',
            index=models.Index(fields=['location'], name='listings_gu_locatio_ee421b_idx'),
        ),
        migrations.AddIndex(
            model_name='hotelprofile',
            index=models.Index(fields=['location'], name='listings_ho_locatio_1cad0c_idx'),
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['price'], name='listings_pa_price_485063_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['room_type'], name='listings_ro_room_ty_190eb5_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['is_available'], name='listings_ro_is_avai_83c669_idx'),
        ),
    ]
