# Generated by Django 6.0.6 on 2026-06-13 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_guideprofile_listings_gu_locatio_ee421b_idx_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='package',
            constraint=models.UniqueConstraint(fields=('guide', 'title'), name='unique_package_per_guide'),
        ),
    ]
