# Generated by Django 5.2.15 on 2026-06-19 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_package_unique_package_per_guide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guideprofile',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='guideprofile',
            name='price_per_day',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10),
        ),
        migrations.AlterField(
            model_name='hotelprofile',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='hotelprofile',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
