# Generated by Django 5.2.15 on 2026-06-22 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_alter_guideprofile_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='description',
        ),
    ]
